---

- name: "Docker: Add Docker's official GPG key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Docker: Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "Docker: Install Docker"
  apt:
    name: docker-ce
    state: present

- name: "Docker: Install docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: "Docker: Add user to Docker group"
  user:
    name: vagrant
    groups: docker
    append: yes

- name: "Docker: Start Docker service"
  service:
    name: docker
    state: started
